version: '2'
services:
  phpapp:
    build: .
    command: initstart
    volumes:
      - .:/var/www/html
    env_file: .env
    ports:
      - "$PHPAPP_PORT:80"
    devices:
      - /dev/gpiomem
    depends_on:
      - db
  phpmyadmin:
    image: ebspace/armhf-phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=$MYSQL_USER
      - PMA_PASSWORD=$MYSQL_PASSWORD
    restart: always
    ports:
      - "$MYSQLADMIN_PORT:80"
    volumes:
      - /sessions
    depends_on:
      - db
  db:
    image: yobasystems/alpine-mariadb:armhf
    restart: always
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    expose:
      - 3306
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata:
